export const apiEndPoints = {

    addAddress:"/api/user/addaddress",
    addBanner:'/api/admin/addbanner',
    addCheckoutAddress:"/api/user/addcheckoutaddress",
    addProducts:'/api/admin/addproducts',
    roomCheck:"/api/admin/roomcheck",
    addRoom:"/api/admin/addroomid",
    deleteRoom:"/api/admin/deleteroom",
    findRoomId:"/api/admin/findroomid",
    adminLogin:"/api/admin/login",
    profileDetails: "/api/Admin/profiledetails",
    uploadImage:"/api/admin/uploadImage",
    getAdminData:'/api/user/getadmindata',
    displayOrders:"/api/admin/displayorders",
    changeStatus:"/api/admin/changestatus",
    primeUsersDetails:"/api/admin/primeusersdetails",
    subscriptionDetails:"/api/admin/subscriptionadminsidesingledata",
    bannerList:'/api/user/bannerlist',
    adminBannerList:"/api/admin/bannerlist",
    userProfileDetails:"/api/user/profiledetails",
    saveBmi:"/api/user/savebmi",
    fetchCartDetails:"/api/user/fetchcartdetails",
    increment:"/api/user/increment",
    decrement:"/api/user/decrement",
    deleteCartProduct:"/api/user/deletecartdata",
    deleteCheckoutAddress:"/api/user/deleteaddress",
    productPurchase:"/api/user/productpurchase",
    varifyPayment: "/api/user/verifyproductpayment",
    contentList:'/api/user/contentlist',
    adminContentList:"/api/admin/contentlist",
    deleteContent:"/api/admin/deletecontent",
    dashboardDetails:"/api/admin/dashboarddetails",
    userProfileAddressEdit:"/api/user/userprofileaddressedit",
    editCheckoutAddress: "/api/user/usercheckoutaddressedit",
    adminFetchProducts:"/api/admin/fetchproduct",
    editProducts:"/api/admin/editproducts",
    editProductWithImage:"/api/admin/editproductswithimage",
    userProfileEditData:"/api/user/userprofileeditdata",
    confirmEmail:"/api/user/conformemail",
    deleteFood:"/api/admin/deletefood",
    adminFetchFood:"/api/admin/fetchfood",
    forgotOtp:"/api/user/forgototp",
    dashBoardDisplayOrders:'/api/admin/dashboarddisplayorders',
    userlist:'/api/admin/userlist',
    displayOrder:'/api/admin/displayorders',
    primecheck:"/api/user/primecheck",
    AdminListProduct:"/api/admin/fetchproducts",
    blockPoducts:"/api/admin/blockproducts",
    unBlockProduct:"/api/admin/unblockproducts",
    adminVideoList:"/api/admin/videolist",
    deleteVideo:"/api/admin/deletevideo",
    login:"/api/user/login",
    googleLogin:"/api/user/googlelogin",
    videoCallNotification:"/api/user/videocallnotification",
    planNotification:"/api/user/plannotification",
    fetchSingleOrder:"/api/admin/fetchsingleorder",
    otp:"/api/user/otp",
    deleteplan:"/api/admin/deleteplan",
    adminPlanList:"/api/admin/planlist",
    userPlanList:"/api/user/planlist",
    planPurchase:"/api/user/purchase",
    planVerifyPayment:"/api/user/verifypayment",
    userAddToCart:"/api/user/addtocarts",
    userfetchProduct: "/api/user/fetchproduct",
    register:"/api/user/register",
    resetPassword:"/api/user/resetpassword",
    userfetchProducts:"/api/user/userfetchproducts",
    priceSort:"/api/user/pricesort",
    userCatogoryFetchProducts: "/api/user/usercatogoryfetchproducts",
    userSideOrder: "/api/user/usersideorderdetails",
    userlists:"/api/admin/userlist",
    blockuser:"/api/admin/blockuser",
    unBlockUser:"/api/admin/unblockuser",
    fetchSubscriptionHistory:"/api/user/fetchsubscriptionhistory",
    userUploadImage:"/api/user/uploadImage",
    planData:"/api/user/plannotification",
    userRoomCheck:'/api/user/roomcheck',
    findRoomIds:"/api/user/findroomid",
    fetchGain:'/api/user/fetchgain',
    fetchLose:"/api/user/fetchlose",
    workouts:"/api/user/videolist"

    
}